# Generated by Django 5.2.8 on 2025-11-25 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('library', '0002_mediaitem_error_log_mediaitem_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                (
                    'complexity',
                    models.PositiveIntegerField(
                        default=1, help_text='Complexity level (1-5)'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'media_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='concepts',
                        to='library.mediaitem',
                    ),
                ),
            ],
        ),
    ]
