# Generated by Django 5.2.8 on 2025-11-25 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('library', '0002_mediaitem_error_log_mediaitem_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                (
                    'complexity',
                    models.PositiveIntegerField(
                        default=1, help_text='Complexity level (1-5)'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'media_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='concepts',
                        to='library.mediaitem',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'front',
                    models.TextField(help_text='Question or front side'),
                ),
                ('back', models.TextField(help_text='Answer or back side')),
                (
                    'reps',
                    models.PositiveIntegerField(
                        default=0, help_text='Number of repetitions'
                    ),
                ),
                (
                    'interval',
                    models.PositiveIntegerField(
                        default=0, help_text='Days until next review'
                    ),
                ),
                (
                    'ease_factor',
                    models.FloatField(
                        default=2.5, help_text='Easiness factor'
                    ),
                ),
                ('last_review', models.DateField(blank=True, null=True)),
                (
                    'next_review',
                    models.DateField(default=django.utils.timezone.now),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'concept',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='flashcards',
                        to='learning.concept',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='flashcards',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
