# Generated by Django 5.2.8 on 2025-12-05 16:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('library', '0003_alter_mediaitem_options_alter_topic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concept',
            options={'verbose_name': 'Concept', 'verbose_name_plural': 'Concepts'},
        ),
        migrations.AlterModelOptions(
            name='flashcard',
            options={'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcards'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={'verbose_name': 'Study Plan', 'verbose_name_plural': 'Study Plans'},
        ),
        migrations.AlterModelOptions(
            name='studyunit',
            options={'ordering': ['order'], 'verbose_name': 'Study Unit', 'verbose_name_plural': 'Study Units'},
        ),
        migrations.AlterField(
            model_name='concept',
            name='complexity',
            field=models.PositiveIntegerField(default=1, help_text='Complexity level (1-5)', verbose_name='Complexity'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='library.mediaitem', verbose_name='Media Item'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='back',
            field=models.TextField(help_text='Answer or back side', verbose_name='Back'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='concept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='learning.concept', verbose_name='Concept'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5, help_text='Easiness factor', verbose_name='Ease Factor'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front',
            field=models.TextField(help_text='Question or front side', verbose_name='Front'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='interval',
            field=models.PositiveIntegerField(default=0, help_text='Days until next review', verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='last_review',
            field=models.DateField(blank=True, null=True, verbose_name='Last Review'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Next Review'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='reps',
            field=models.PositiveIntegerField(default=0, help_text='Number of repetitions', verbose_name='Repetitions'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='learning.concept', verbose_name='Concept'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_data',
            field=models.JSONField(help_text='JSON structure with question, options, correct_answer, explanation', verbose_name='Question Data'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('open', 'Open Answer')], default='multiple_choice', max_length=20, verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='media_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='library.mediaitem', verbose_name='Media Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='library.topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='studyunit',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_units', to='learning.concept', verbose_name='Concept'),
        ),
        migrations.AlterField(
            model_name='studyunit',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='studyunit',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='studyunit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learning.studyplan', verbose_name='Study Plan'),
        ),
    ]
