# Generated by Django 5.2.8 on 2025-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_tutorchatsession_tutorchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorchatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=100, verbose_name='Title'),
        ),
    ]
