# Generated by Django 5.2.8 on 2025-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_tutorchatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorchatsession',
            name='context_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Context ID'),
        ),
        migrations.AddField(
            model_name='tutorchatsession',
            name='context_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Context Type'),
        ),
    ]
