# Generated by Django 5.2.8 on 2025-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_tutorchatsession_context_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
