# Generated by Django 5.2.8 on 2025-11-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_engine', models.CharField(choices=[('openai', 'OpenAI Whisper'), ('whisperx', 'WhisperX (Local)'), ('t_one', 'T-One (Local)')], default='whisperx', help_text='Select the engine for audio transcription.', max_length=20)),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='openai', help_text='Select the LLM provider for summarization.', max_length=20)),
            ],
            options={
                'verbose_name': 'Project Configuration',
                'verbose_name_plural': 'Project Configuration',
            },
        ),
    ]
