# Generated by Django 5.2.8 on 2025-11-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='chat_prompt',
        ),
    ]
