# Generated by Django 5.2.8 on 2025-11-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsettings',
            options={'verbose_name': 'Settings'},
        ),
    ]
