# Generated by Django 5.2.8 on 2025-12-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_projectsettings_chat_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='concept_extraction_prompt',
            field=models.TextField(default='You are an expert educational analyst. Your goal is to extract key concepts from the provided text.\nExtract atomic concepts that are suitable for creating flashcards and study units.', help_text='System prompt for Concept Extraction Agent.', verbose_name='Concept Extraction Prompt'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='plan_generation_prompt',
            field=models.TextField(default='You are an expert curriculum designer.\nCreate a logical, step-by-step study plan based on the provided concepts.\nOrder the units from simplest to most complex. Ensure dependencies are respected.', help_text='System prompt for Study Plan Generation Agent.', verbose_name='Plan Generation Prompt'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='quiz_generation_prompt',
            field=models.TextField(default="You are an expert exam creator.\nGenerate multiple-choice questions to test the user's understanding of the concept.\nEnsure distractors (wrong answers) are plausible but incorrect.", help_text='System prompt for Quiz Generation Agent.', verbose_name='Quiz Generation Prompt'),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='tutor_prompt',
            field=models.TextField(default="You are a helpful AI Tutor. Use the available tools to answer the user's questions.", help_text='System prompt for Tutor Agent.', verbose_name='Tutor Prompt'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], default='openai', help_text='Select LLM provider.', max_length=20, verbose_name='LLM Provider'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='summarization_prompt',
            field=models.TextField(default='Please provide a concise summary of the following text.', help_text='System prompt for Summarization.', verbose_name='Summarization Prompt'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='transcription_engine',
            field=models.CharField(choices=[('openai', 'OpenAI Whisper'), ('whisperx', 'WhisperX (Local)')], default='whisperx', help_text='Select transcription engine.', max_length=20, verbose_name='Transcription Engine'),
        ),
    ]
