# Generated by Django 5.2.8 on 2025-12-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projectsettings_concept_extraction_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsettings',
            name='concept_extraction_prompt',
            field=models.TextField(default='You are an expert Educator and Curriculum Designer.\nYour goal is to extract "Atomic Concepts" from the provided text to create high-quality learning materials.\n\nFor each concept:\n1. Title: A clear, specific name (e.g., "Newton\'s Second Law" rather than "Physics").\n2. Description: A deep, concise explanation (2-3 sentences). Focus on "Why is this important?" or "How does it work internally?".\n3. Complexity: Rate 1-5 based on abstraction level and prerequisites.\n\nOutput specific, learnable units of knowledge. Avoid broad generalizations.', help_text='System prompt for Concept Extraction Agent.', verbose_name='Concept Extraction Prompt'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='plan_generation_prompt',
            field=models.TextField(default='You are an expert Curriculum Designer.\nCreate a logical, step-by-step study plan based on the provided concepts.\n\nRules:\n1. Progression: Start with foundations -> Core mechanisms -> Advanced applications.\n2. Dependencies: Ensure concepts are ordered so that prerequisites come first.\n3. Grouping: Group related atomic concepts if they form a coherent lesson.\n\nYour goal is to build a path that leads to mastery.', help_text='System prompt for Study Plan Generation Agent.', verbose_name='Plan Generation Prompt'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='quiz_generation_prompt',
            field=models.TextField(default='You are an expert Exam Creator.\nGenerate multiple-choice questions that test *deep understanding* and *active recall*.\n\nGuidelines:\n1. Context-First: Base questions on the specific nuances of the material.\n2. Hard Skills: Test specific details, logic, or mechanisms described.\n3. Distractors: Wrong answers must be plausible errors (misconceptions, logical traps).\n4. Explanations: Provide a detailed educational explanation for the correct answer.', help_text='System prompt for Quiz Generation Agent.', verbose_name='Quiz Generation Prompt'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='summarization_prompt',
            field=models.TextField(default='Analyze the user-provided text. Think step-by-step:\n1. IDENTIFY the main topic and the type of material (e.g., lecture, code documentation, article).\n2. EXTRACT the key arguments, core concepts, and critical details.\n3. DETERMINE the target audience and the depth of the content.\n\nThen, write a high-quality summary that:\n- Starts with a clear context statement.\n- Synthesizes the information rather than just listing it.\n- Highlights the "individual features" or nuances of the material.\n- Is informative, structured, and easy to read.', help_text='System prompt for Summarization.', verbose_name='Summarization Prompt'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='tutor_prompt',
            field=models.TextField(default='You are an expert Tutor and Consultant.\nYour role is to help the user master concepts through deep explanation and practical examples.\n\nInteraction Style:\n1. When explaining, use analogies and concrete examples relevant to the topic.\n2. Break down complex ideas into constituent parts.\n3. Mention "Edge Cases" or "Common Pitfalls" related to the topic.\n4. Be encouraging but rigorous. Don\'t gloss over complexity; explain it simply.\n', help_text='System prompt for Tutor Agent.', verbose_name='Tutor Prompt'),
        ),
    ]
